export interface LinkPreset {
  id: string;
  title: string;
  shortLabel: string;
  category: 'contact' | 'social' | 'business' | 'content';
  categoryLabel: string;
  defaultUrl: string;
  placeholder: string;
  defaultGroup: string;
  bgClass: string;
  textClass: string;
  borderClass: string;
  emoji: string;
  helperTip: string;
}

export const LINK_CATEGORIES = [
  { id: 'all', label: '⭐ Todos los Atajos' },
  { id: 'business', label: '📍 Negocio & Reseñas' },
  { id: 'social', label: '📱 Redes Sociales' },
  { id: 'contact', label: '💬 Contacto Directo' },
  { id: 'content', label: '🎵 Música & Agenda' },
] as const;

export const POPULAR_LINK_PRESETS: LinkPreset[] = [
  // =========================================================================
  // NEGOCIOS, GOOGLE MAPS Y RESEÑAS
  // =========================================================================
  {
    id: 'google-review',
    title: 'Califícanos en Google Maps (5★)',
    shortLabel: '⭐ Reseña en Google Maps',
    category: 'business',
    categoryLabel: 'Negocio & Reseñas',
    defaultUrl: 'https://search.google.com/local/writereview?placeid=',
    placeholder: 'https://search.google.com/local/writereview?placeid=... o link corto g.page/r/.../review',
    defaultGroup: 'Opiniones & Reseñas',
    bgClass: 'bg-amber-500/15 hover:bg-amber-500/25',
    textClass: 'text-amber-300 font-bold',
    borderClass: 'border-amber-500/40',
    emoji: '⭐',
    helperTip: 'Enlace directo para que tus clientes califiquen tu ficha de Google Maps con 5 estrellas.',
  },
  {
    id: 'google-maps',
    title: 'Cómo Llegar / Ubicación en Google Maps',
    shortLabel: '📍 Ubicación Google Maps',
    category: 'business',
    categoryLabel: 'Negocio & Reseñas',
    defaultUrl: 'https://maps.google.com/?q=',
    placeholder: 'https://maps.app.goo.gl/... o https://maps.google.com/?q=Tu+Direccion',
    defaultGroup: 'Ubicación',
    bgClass: 'bg-red-500/15 hover:bg-red-500/25',
    textClass: 'text-rose-300 font-bold',
    borderClass: 'border-red-500/40',
    emoji: '📍',
    helperTip: 'Abre la ruta y dirección exacta de tu local o sucursal en la app de Google Maps.',
  },
  {
    id: 'website',
    title: 'Sitio Web Oficial',
    shortLabel: '🌐 Sitio Web Oficial',
    category: 'business',
    categoryLabel: 'Negocio & Reseñas',
    defaultUrl: 'https://',
    placeholder: 'https://tuempresa.com',
    defaultGroup: 'Principal',
    bgClass: 'bg-teal-500/15 hover:bg-teal-500/25',
    textClass: 'text-teal-300 font-bold',
    borderClass: 'border-teal-500/40',
    emoji: '🌐',
    helperTip: 'Dirección oficial de tu página web, tienda online o landing page.',
  },
  {
    id: 'catalog-menu',
    title: 'Menú Digital / Catálogo de Productos',
    shortLabel: '📋 Menú / Catálogo Digital',
    category: 'business',
    categoryLabel: 'Negocio & Reseñas',
    defaultUrl: 'https://',
    placeholder: 'https://tudominio.com/menu o enlace PDF de Google Drive',
    defaultGroup: 'Menú & Catálogo',
    bgClass: 'bg-orange-500/15 hover:bg-orange-500/25',
    textClass: 'text-orange-300 font-bold',
    borderClass: 'border-orange-500/40',
    emoji: '📋',
    helperTip: 'Enlace directo a tu carta, menú de restaurante, catálogo PDF o tienda.',
  },
  {
    id: 'tripadvisor',
    title: 'Opiniones en TripAdvisor',
    shortLabel: '🦉 TripAdvisor',
    category: 'business',
    categoryLabel: 'Negocio & Reseñas',
    defaultUrl: 'https://www.tripadvisor.com/',
    placeholder: 'https://www.tripadvisor.com/Restaurant_Review-...',
    defaultGroup: 'Opiniones & Reseñas',
    bgClass: 'bg-emerald-500/15 hover:bg-emerald-500/25',
    textClass: 'text-emerald-300 font-bold',
    borderClass: 'border-emerald-500/40',
    emoji: '🦉',
    helperTip: 'Perfil de TripAdvisor para hoteles, restaurantes y turismo.',
  },

  // =========================================================================
  // CONTACTO DIRECTO & MENSAJERÍA
  // =========================================================================
  {
    id: 'whatsapp',
    title: 'Enviar Mensaje por WhatsApp',
    shortLabel: '💬 WhatsApp',
    category: 'contact',
    categoryLabel: 'Contacto Directo',
    defaultUrl: 'https://wa.me/',
    placeholder: 'https://wa.me/5215512345678 o solo tu número con código de país',
    defaultGroup: 'Contacto',
    bgClass: 'bg-emerald-600/20 hover:bg-emerald-600/30',
    textClass: 'text-emerald-300 font-bold',
    borderClass: 'border-emerald-500/50',
    emoji: '💬',
    helperTip: 'Abre WhatsApp al instante con tu número de teléfono (incluye código de país).',
  },
  {
    id: 'phone-call',
    title: 'Llamar por Teléfono Directo',
    shortLabel: '📞 Llamada Telefónica',
    category: 'contact',
    categoryLabel: 'Contacto Directo',
    defaultUrl: 'tel:',
    placeholder: 'tel:+525512345678 o 55-1234-5678',
    defaultGroup: 'Contacto',
    bgClass: 'bg-sky-500/15 hover:bg-sky-500/25',
    textClass: 'text-sky-300 font-bold',
    borderClass: 'border-sky-500/40',
    emoji: '📞',
    helperTip: 'Marca inmediatamente tu número de teléfono desde el celular del cliente.',
  },
  {
    id: 'email',
    title: 'Enviar Correo Electrónico',
    shortLabel: '✉️ Correo Electrónico',
    category: 'contact',
    categoryLabel: 'Contacto Directo',
    defaultUrl: 'mailto:',
    placeholder: 'contacto@tuempresa.com',
    defaultGroup: 'Contacto',
    bgClass: 'bg-purple-500/15 hover:bg-purple-500/25',
    textClass: 'text-purple-300 font-bold',
    borderClass: 'border-purple-500/40',
    emoji: '✉️',
    helperTip: 'Abre el cliente de correo predeterminado (Gmail, Outlook, Mail).',
  },
  {
    id: 'telegram',
    title: 'Canal / Chat de Telegram',
    shortLabel: '✈️ Telegram',
    category: 'contact',
    categoryLabel: 'Contacto Directo',
    defaultUrl: 'https://t.me/',
    placeholder: 'https://t.me/tu_usuario o tu canal',
    defaultGroup: 'Contacto',
    bgClass: 'bg-cyan-500/15 hover:bg-cyan-500/25',
    textClass: 'text-cyan-300 font-bold',
    borderClass: 'border-cyan-500/40',
    emoji: '✈️',
    helperTip: 'Enlace a tu usuario personal o canal de Telegram.',
  },
  {
    id: 'sms',
    title: 'Enviar Mensaje SMS',
    shortLabel: '📱 Mensaje SMS',
    category: 'contact',
    categoryLabel: 'Contacto Directo',
    defaultUrl: 'sms:',
    placeholder: 'sms:+525512345678',
    defaultGroup: 'Contacto',
    bgClass: 'bg-blue-500/15 hover:bg-blue-500/25',
    textClass: 'text-blue-300 font-bold',
    borderClass: 'border-blue-500/40',
    emoji: '📱',
    helperTip: 'Abre la app de mensajería SMS en teléfonos móviles.',
  },

  // =========================================================================
  // REDES SOCIALES MÁS POPULARES
  // =========================================================================
  {
    id: 'instagram',
    title: 'Instagram',
    shortLabel: '📸 Instagram',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://instagram.com/',
    placeholder: 'https://instagram.com/tu_usuario o @tu_usuario',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-pink-500/15 hover:bg-pink-500/25',
    textClass: 'text-pink-300 font-bold',
    borderClass: 'border-pink-500/40',
    emoji: '📸',
    helperTip: 'Perfil de Instagram para ver tus fotos, reels e historias.',
  },
  {
    id: 'tiktok',
    title: 'TikTok',
    shortLabel: '🎵 TikTok',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://tiktok.com/@',
    placeholder: 'https://tiktok.com/@tu_usuario',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-slate-800 hover:bg-slate-700',
    textClass: 'text-rose-300 font-bold',
    borderClass: 'border-rose-500/40',
    emoji: '🎵',
    helperTip: 'Canal oficial de videos cortos en TikTok.',
  },
  {
    id: 'facebook',
    title: 'Facebook (Página / Perfil)',
    shortLabel: '📘 Facebook',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://facebook.com/',
    placeholder: 'https://facebook.com/tu.pagina.oficial',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-indigo-500/15 hover:bg-indigo-500/25',
    textClass: 'text-indigo-300 font-bold',
    borderClass: 'border-indigo-500/40',
    emoji: '📘',
    helperTip: 'Fanpage o perfil empresarial de Facebook.',
  },
  {
    id: 'linkedin',
    title: 'LinkedIn (Perfil / Empresa)',
    shortLabel: '💼 LinkedIn',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://linkedin.com/in/',
    placeholder: 'https://linkedin.com/in/tu-perfil o https://linkedin.com/company/tu-empresa',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-sky-600/15 hover:bg-sky-600/25',
    textClass: 'text-sky-300 font-bold',
    borderClass: 'border-sky-500/40',
    emoji: '💼',
    helperTip: 'Perfil profesional, CV y red de negocios en LinkedIn.',
  },
  {
    id: 'youtube',
    title: 'Canal de YouTube',
    shortLabel: '🎥 YouTube',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://youtube.com/@',
    placeholder: 'https://youtube.com/@tu_canal',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-red-600/15 hover:bg-red-600/25',
    textClass: 'text-red-300 font-bold',
    borderClass: 'border-red-500/40',
    emoji: '🎥',
    helperTip: 'Canal de videos, tutoriales o transmisiones en YouTube.',
  },
  {
    id: 'x-twitter',
    title: 'X (Twitter)',
    shortLabel: '𝕏 X (Twitter)',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://x.com/',
    placeholder: 'https://x.com/tu_usuario',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-slate-800 hover:bg-slate-700',
    textClass: 'text-slate-200 font-bold',
    borderClass: 'border-slate-600',
    emoji: '𝕏',
    helperTip: 'Cuenta oficial de noticias y publicaciones en X.',
  },
  {
    id: 'pinterest',
    title: 'Pinterest',
    shortLabel: '📌 Pinterest',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://pinterest.com/',
    placeholder: 'https://pinterest.com/tu_usuario',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-rose-700/15 hover:bg-rose-700/25',
    textClass: 'text-rose-300 font-bold',
    borderClass: 'border-rose-600/40',
    emoji: '📌',
    helperTip: 'Tableros de inspiración, moda, diseño y fotografía.',
  },
  {
    id: 'threads',
    title: 'Threads',
    shortLabel: '🧵 Threads',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    defaultUrl: 'https://threads.net/@',
    placeholder: 'https://threads.net/@tu_usuario',
    defaultGroup: 'Redes Sociales',
    bgClass: 'bg-slate-800 hover:bg-slate-700',
    textClass: 'text-slate-300 font-bold',
    borderClass: 'border-slate-700',
    emoji: '🧵',
    helperTip: 'Comunidad de conversación de Instagram Threads.',
  },

  // =========================================================================
  // MÚSICA, AGENDA, CITAS Y PAGOS
  // =========================================================================
  {
    id: 'calendly',
    title: 'Agendar Cita / Reunión (Calendly / Cal.com)',
    shortLabel: '📅 Agendar Cita',
    category: 'content',
    categoryLabel: 'Música & Agenda',
    defaultUrl: 'https://calendly.com/',
    placeholder: 'https://calendly.com/tu-usuario/reunion-30min',
    defaultGroup: 'Citas & Reservas',
    bgClass: 'bg-blue-600/15 hover:bg-blue-600/25',
    textClass: 'text-blue-300 font-bold',
    borderClass: 'border-blue-500/40',
    emoji: '📅',
    helperTip: 'Permite que tus clientes agenden citas automáticamente en tu calendario.',
  },
  {
    id: 'spotify',
    title: 'Spotify (Artista / Playlist / Podcast)',
    shortLabel: '🎧 Spotify / Podcast',
    category: 'content',
    categoryLabel: 'Música & Agenda',
    defaultUrl: 'https://open.spotify.com/',
    placeholder: 'https://open.spotify.com/artist/... o playlist/...',
    defaultGroup: 'Música & Podcast',
    bgClass: 'bg-emerald-500/15 hover:bg-emerald-500/25',
    textClass: 'text-emerald-300 font-bold',
    borderClass: 'border-emerald-500/40',
    emoji: '🎧',
    helperTip: 'Música, canciones, álbumes o episodios de podcast en Spotify.',
  },
  {
    id: 'apple-music',
    title: 'Apple Music / Podcasts',
    shortLabel: '🍎 Apple Music',
    category: 'content',
    categoryLabel: 'Música & Agenda',
    defaultUrl: 'https://music.apple.com/',
    placeholder: 'https://music.apple.com/album/...',
    defaultGroup: 'Música & Podcast',
    bgClass: 'bg-rose-500/15 hover:bg-rose-500/25',
    textClass: 'text-rose-300 font-bold',
    borderClass: 'border-rose-500/40',
    emoji: '🍎',
    helperTip: 'Música y podcasts en la plataforma de Apple.',
  },
  {
    id: 'paypal',
    title: 'Pagar con PayPal / Enviar Pago',
    shortLabel: '💳 PayPal / Pagos',
    category: 'content',
    categoryLabel: 'Música & Agenda',
    defaultUrl: 'https://paypal.me/',
    placeholder: 'https://paypal.me/tuusuario',
    defaultGroup: 'Pagos & Donaciones',
    bgClass: 'bg-indigo-600/15 hover:bg-indigo-600/25',
    textClass: 'text-indigo-300 font-bold',
    borderClass: 'border-indigo-500/40',
    emoji: '💳',
    helperTip: 'Enlace directo de cobro o donaciones con PayPal Me.',
  },
];
